nfq_weather:
# TODO: Uncomment the following once Configuration.php is implemented
    provider: delegating
    providers:
        openweathermap:
            api_key: '54ed3d0b45b21a024d854a1bbcd976a0'
        delegating:
            providers:
                - yahoo
                - openweathermap
