<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\HomeController' shared autowired service.

return $this->services['App\Controller\HomeController'] = new \App\Controller\HomeController();
