parameters:
    nfq_weather.provider.openweathermap: 0
    nfq_weather.provider.yahoo:          0
    nfq_weather.provider.delegating:     0

services:
    _defaults:
        public: false

    nfq_weather.provider.openweathermap:
                class: Nfq\WeatherBundle\OpenWeatherMapWeatherProvider
                arguments: ["%nfq_weather.provider.openweathermap%"]

    nfq_weather.provider.yahoo:
            class: Nfq\WeatherBundle\YahooWeatherProvider
            arguments: ["%nfq_weather.provider.yahoo%"]

    nfq_weather.provider.delegating:
                class: Nfq\WeatherBundle\DelegatingWeatherProvider
                arguments: ["%nfq_weather.provider.delegating%"]