services:
    _defaults:
        public: true

    nfq_weather.provider.openweathermap:
                class: Nfq\WeatherBundle\OpenWeatherMapWeatherProvider
                arguments: ["%providers.openweathermap.apikey%"]

    nfq_weather.provider.yahoo:
            class: Nfq\WeatherBundle\YahooWeatherProvider
            arguments: ["%nfq_weather.provider.yahoo%"]

    nfq_weather.provider.delegating:
                class: Nfq\WeatherBundle\DelegatingWeatherProvider
                arguments: ["%nfq_weather.provider.delegating%"]