<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\GiftType' shared autowired service.

return $this->privates['App\Form\GiftType'] = new \App\Form\GiftType();
