<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\GiftListRepository' shared autowired service.

return $this->privates['App\Repository\GiftListRepository'] = new \App\Repository\GiftListRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
